version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker build -t briandemaio/reactapp -f Dockerfile.dev
          docker run briandemaio/reactapp npm run test -- --coverage
          docker build -t briandemaio/reactapp:lastest .
          docker run -d --name briandemaio/reactapp:latest
        # docker exec briandemaio/reactapp:latest curl --retry 10 --retry-connrefused http://localhost:8080
