version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker build -t hereiam123/reactapp:dev -f Dockerfile.dev .
          docker run -e CI=true hereiam123/reactapp:dev npm run test -- --coverage
          docker build -t hereiam123/reactapp:lastest .
          echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
          docker push hereiam123/reactapp:lastest
      - run:
          name: Deploy app to Digital Ocean Server via Docker
          command: |
            ssh -o StrictHostKeyChecking=no circleci@$DEPLOY_IP "/bin/bash ./deploy_app.sh hereiam123/reactapp:lastest"
